package com.projkts.notbored.repository

import com.projkts.notbored.model.Activity
import com.projkts.notbored.model.Category

class ActivityRepository {
    companion object {
        fun getAll(): List<Activity> {
            return listOf<Activity>(
                Activity("Visiting a cancer hospital to cheer them up", 1 , 0.0, Category.CHARITY ),
                Activity("Donate good clothes you no longer wear", 2 , 0.1, Category.CHARITY ),
                Activity("Donating food to a non-profit organization", 3 , 0.2, Category.CHARITY ),
                Activity("Donating money to a street beggar", 4 , 0.3, Category.CHARITY ),
                Activity("Visit a nursing home and spend 1h with the elderly", 5 , 0.4, Category.CHARITY ),
                Activity("Help the neighbor with something", 6 , 0.5, Category.CHARITY ),
                Activity("Register with an institution to donate blood", 7 , 0.6, Category.CHARITY ),
                Activity("Help 3 people today", 8 , 0.7, Category.CHARITY ),
                Activity("Buying a Snack for Someone in Need", 9 , 0.8, Category.CHARITY ),
                Activity("Help someone with their knowledge by teaching something", 10 , 0.9, Category.CHARITY ),
                Activity("Organize the month's schedule", 10 , 1.0, Category.CHARITY ),
                Activity("List upcoming tasks", 1 , 0.0, Category.BUSYWORK ),
                Activity("Read an article about the weather", 2 , 0.1, Category.BUSYWORK ),
                Activity("Keep your desk organized", 3 , 0.2, Category.BUSYWORK ),
                Activity("Make a word search", 4 , 0.3, Category.BUSYWORK ),
                Activity("Play the solitaire game", 5 , 0.4, Category.BUSYWORK ),
                Activity("Meditate for 5 minutes", 6 , 0.5, Category.BUSYWORK ),
                Activity("Run for a block today", 7 , 0.6, Category.BUSYWORK ),
                Activity("Think and write down improvements for your home", 8 , 0.7, Category.BUSYWORK ),
                Activity("Think and write down improvements for your workgroup", 9 , 0.8, Category.BUSYWORK ),
                Activity("Create a logic challenge to solve as a group", 10 , 0.9, Category.BUSYWORK ),
                Activity("Cycling with colleagues", 10 , 1.0, Category.BUSYWORK ),
                Activity("Write letters and tickets", 1 , 0.0, Category.SOCIAL ),
                Activity("Support for women victims of violence", 2 , 0.1, Category.SOCIAL),
                Activity("Combating racial inequality", 3 , 0.2, Category.SOCIAL ),
                Activity("Support for homeless people.", 4 , 0.3, Category.SOCIAL),
                Activity("Education of children and youth.", 5 , 0.4, Category.SOCIAL ),
                Activity("Preservation of the environment and nature", 6 , 0.5, Category.SOCIAL),
                Activity("Welcoming and improving the quality of life of the elderly", 7 , 0.6, Category.SOCIAL ),
                Activity("Inclusion of people with disabilities", 8 , 0.7, Category.SOCIAL ),
                Activity("Support for drug addicts", 9 , 0.8, Category.SOCIAL ),
                Activity("Combating Poverty", 10 , 0.9, Category.SOCIAL),
                Activity("Combating child abuse and supporting victims", 10 , 1.0, Category.SOCIAL),
                Activity("Simple DIY decoration to change the face of the office", 1 , 0.0, Category.DIY ),
                Activity("Make a toy box", 2 , 0.1, Category.DIY),
                Activity("Make a decorative plant pot", 3 , 0.2, Category.DIY),
                Activity("Make a toy", 4 , 0.3, Category.DIY),
                Activity("Make a simple light fixture", 5 , 0.4, Category.DIY ),
                Activity("Create a game", 6 , 0.5, Category.DIY),
                Activity("Create a painting", 7 , 0.6, Category.DIY ),
                Activity("Make a pet bed", 8 , 0.7, Category.DIY ),
                Activity("Make a decorative bottle", 9 , 0.8, Category.DIY),
                Activity("Make a Button Frame", 10 , 0.9, Category.DIY),
                Activity("Make a cutlery holder", 10 , 1.0, Category.DIY),
                Activity("Sing", 1 , 0.0, Category.CHARITY),
                Activity("Sing", 2 , 0.1, Category.CHARITY),
                Activity("Sing", 3 , 0.2, Category.CHARITY),
                Activity("Sing", 4 , 0.3, Category.CHARITY),
                Activity("Sing", 5 , 0.4, Category.CHARITY),
                Activity("Sing", 6 , 0.5, Category.CHARITY),
                Activity("Sing", 7 , 0.6, Category.CHARITY),
                Activity("Sing", 8 , 0.7, Category.CHARITY),
                Activity("Sing", 9 , 0.8, Category.CHARITY),
                Activity("Sing", 10 , 0.9, Category.CHARITY),
                Activity("Sing", 10 , 1.0, Category.CHARITY),
                Activity("Sing", 1 , 0.0, Category.COOKING),
                Activity("Sing", 2 , 0.1, Category.COOKING),
                Activity("Sing", 3 , 0.2, Category.COOKING),
                Activity("Sing", 4 , 0.3, Category.COOKING),
                Activity("Sing", 5 , 0.4, Category.COOKING),
                Activity("Sing", 6 , 0.5, Category.COOKING),
                Activity("Sing", 7 , 0.6, Category.COOKING),
                Activity("Sing", 8 , 0.7, Category.COOKING),
                Activity("Sing", 9 , 0.8, Category.COOKING),
                Activity("Sing", 10 , 0.9, Category.COOKING),
                Activity("Sing", 10 , 1.0, Category.COOKING),
                Activity("Sing", 1 , 0.0, Category.RECREATIONAL),
                Activity("Sing", 2 , 0.1, Category.RECREATIONAL),
                Activity("Sing", 3 , 0.2, Category.RECREATIONAL),
                Activity("Sing", 4 , 0.3, Category.RECREATIONAL),
                Activity("Sing", 5 , 0.4, Category.RECREATIONAL),
                Activity("Sing", 6 , 0.5, Category.RECREATIONAL),
                Activity("Sing", 7 , 0.6, Category.RECREATIONAL),
                Activity("Sing", 8 , 0.7, Category.RECREATIONAL),
                Activity("Sing", 9 , 0.8, Category.RECREATIONAL),
                Activity("Sing", 10 , 0.9, Category.RECREATIONAL),
                Activity("Sing", 10 , 1.0, Category.RECREATIONAL),
                Activity("Meditation for 15 minutes", 1 , 0.0, Category.RELAXATION),
                Activity("Sing your favorite song", 2 , 0.1, Category.RELAXATION),
                Activity("Lie on the couch and rest 30 minutes", 3 , 0.2, Category.RELAXATION),
                Activity("Take a nap already", 4 , 0.3, Category.RELAXATION),
                Activity("Stretch your arms, legs and spine", 5 , 0.4, Category.RELAXATION),
                Activity("Wear comfortable clothes", 6 , 0.5, Category.RELAXATION),
                Activity("Get a facial massage", 7 , 0.6, Category.RELAXATION),
                Activity("Take a hot bath", 8 , 0.7, Category.RELAXATION),
                Activity("Sing", 9 , 0.8, Category.RELAXATION),
                Activity("Sing", 10 , 0.9, Category.RELAXATION),
                Activity("Sing", 10 , 1.0, Category.RELAXATION),
                Activity("Sing", 1 , 0.0, Category.MUSIC),
                Activity("Sing", 2 , 0.1, Category.MUSIC),
                Activity("Sing", 3 , 0.2, Category.MUSIC),
                Activity("Sing", 4 , 0.3, Category.MUSIC),
                Activity("Sing", 5 , 0.4, Category.MUSIC),
                Activity("Sing", 6 , 0.5, Category.MUSIC),
                Activity("Sing", 7 , 0.6, Category.MUSIC),
                Activity("Sing", 8 , 0.7, Category.MUSIC),
                Activity("Sing", 9 , 0.8, Category.MUSIC),
                Activity("Sing", 10 , 0.9, Category.MUSIC),
                Activity("Sing", 10 , 1.0, Category.MUSIC),
                Activity("Sing", 1 , 0.0, Category.BUSYWORK),
                Activity("Sing", 2 , 0.1, Category.BUSYWORK),
                Activity("Sing", 3 , 0.2, Category.BUSYWORK),
                Activity("Sing", 4 , 0.3, Category.BUSYWORK),
                Activity("Sing", 5 , 0.4, Category.BUSYWORK),
                Activity("Sing", 6 , 0.5, Category.BUSYWORK),
                Activity("Sing", 7 , 0.6, Category.BUSYWORK),
                Activity("Sing", 8 , 0.7, Category.BUSYWORK),
                Activity("Sing", 9 , 0.8, Category.BUSYWORK),
                Activity("Sing", 10 , 0.9, Category.BUSYWORK),
                Activity("Sing", 10 , 1.0, Category.BUSYWORK),
                )
        }
    }
}
